/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pctAdivinha;

import java.awt.Font;

/**
 *
 * @author max
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        lblGenio.setText("<html>Tente adivinhar o numero que estou pensando! De 0 a 5 </html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jsDig = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pctAdivinha/imagens/genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, 380));

        lblGenio.setFont(new java.awt.Font("Ubuntu", 3, 12)); // NOI18N
        lblGenio.setText("<html>Tente adivinhar o numero que estou pensando! De 0 a 5 </html>");
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pctAdivinha/imagens/balao-de-fala-transparente2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 150));

        jLabel1.setText("Digite um valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

        jsDig.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        getContentPane().add(jsDig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 30));

        jButton1.setText("Palpite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double pensamento = Math.random();
        int valPens = (int) (0+pensamento * (5-0)); //numero pensado pelo genio entre 0 e 5
        
        int digi = Integer.parseInt(jsDig.getValue().toString());//numero digitado pelo usuario
        
      /*  if (digi == valPens){
            lblGenio.setText("<html>número errado! eu pensei no valor "+valPens+"</html>" );        
        }
        else{
            lblGenio.setText("Parabéns, você acertou!");*/
      
      String f1 = "<html>Acertou!</html>";
      String f2 = "<html> Numero errado, eu pensei em "+ valPens+"</html>";
      
      String res = (valPens == digi)? f1:f2;
      
      lblGenio.setFont(new Font("Arial Black", Font.PLAIN,12));
      
      lblGenio.setText(res);
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jsDig;
    private javax.swing.JLabel lblGenio;
    // End of variables declaration//GEN-END:variables
}
